name: Latest YouTube Videos
on:
  schedule:
    # This runs every 6 hours to keep your README fresh
    - cron: '0 */6 * * *'
  workflow_dispatch: # This allows you to run it manually to see results immediately

jobs:
  update-readme-with-youtube:
    name: Update README with latest videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxWZ2GteikwcJZhefRtxaXg"
          max_post_count: 5
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$id/mqdefault.jpg"></a></td><td><a href="$url">$title</a><br/>$date</td></tr></table>'
