name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update README with latest videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxWZ2GteikwcJZhefRtxaXg"
          max_post_count: 4
          # This template puts them in a clean inline-block layout
          template: '[![$title](https://i.ytimg.com/vi/$id/mqdefault.jpg)]($url) '
