name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Sync YouTube Thumbnails and Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup & Clean Folders
        run: |
          rm -rf youtube-thumbnails
          mkdir -p youtube-thumbnails

      - name: Pull YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCxWZ2GteikwcJZhefRtxaXg"
          max_post_count: 4
          template: '<a href="$url"><img src="youtube-thumbnails/$id.jpg" width="180"></a> '

      - name: Download Thumbnails
        run: |
          grep -oP 'youtube-thumbnails/\K[^.]+' README.md | while read -r id ; do
            curl -L -f -sS -o "youtube-thumbnails/$id.jpg" "https://i.ytimg.com/vi/$id/mqdefault.jpg"
          done

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add youtube-thumbnails/ README.md
          git commit -m "Refresh YouTube feed and thumbnails" || exit 0
          git push
